/*******************************************************************************
 * fermat_aut_field.m
 *
 * Determine the field over which the automorphisms of the Fermat quartic
 * x^4 + y^4 + z^4 = 0 are defined, by computing Aut(C) over F_p for
 * various primes p.
 ******************************************************************************/

// Over Q, the full automorphism group is (Z/4Z)^2 ⋊ S_3 of order 96.
// The coordinate permutations (S_3) are defined over Q.
// Multiplying coordinates by i = sqrt(-1) requires Q(i).
// So we expect all 96 automorphisms to be defined over Q(i).

// Let's verify by computing |Aut(C)| over F_p for various primes.
// Over F_p, we get the full geometric automorphism group iff F_p contains
// all needed roots of unity (here, 4th roots of unity, i.e., p ≡ 1 mod 4).

printf "=== Fermat quartic: x^4 + y^4 + z^4 = 0 ===\n\n";

printf "Computing |Aut(C)| over F_p for various primes:\n";
printf "%-8o %-12o %-10o\n", "p", "p mod 4", "|Aut|";
printf "------------------------------------\n";

for p in [3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73] do
    Fp := GF(p);
    P2<x,y,z> := ProjectiveSpace(Fp, 2);
    C := Curve(P2, x^4 + y^4 + z^4);
    if not IsNonsingular(C) then
        printf "%-8o SINGULAR\n", p;
        continue;
    end if;
    aut := AutomorphismGroup(C);
    printf "%-8o %-12o %-10o\n", p, p mod 4, #aut;
end for;

printf "\n=== Analysis ===\n";
printf "If p ≡ 1 (mod 4): F_p contains sqrt(-1), expect |Aut| = 96\n";
printf "If p ≡ 3 (mod 4): F_p does NOT contain sqrt(-1), expect |Aut| < 96\n";
printf "\nConclusion: automorphisms are defined over Q(i) = Q(sqrt(-1)).\n";

// Also verify directly: the automorphisms are generated by
//   sigma: (x:y:z) -> (y:z:x)          [order 3, defined over Q]
//   tau:   (x:y:z) -> (y:x:z)          [order 2, defined over Q]
//   mu:    (x:y:z) -> (i*x : y : z)    [order 4, needs Q(i)]
//   nu:    (x:y:z) -> (x : i*y : z)    [order 4, needs Q(i)]
// These generate (Z/4Z)^2 ⋊ S_3 of order 96.

printf "\n=== Explicit generators over Q(i) ===\n";
K<i> := QuadraticField(-1);
P2K<x,y,z> := ProjectiveSpace(K, 2);
CK := Curve(P2K, x^4 + y^4 + z^4);
autK := AutomorphismGroup(CK);
printf "|Aut(C/Q(i))| = %o\n", #autK;

// Also check over Q itself
P2Q<x,y,z> := ProjectiveSpace(Rationals(), 2);
CQ := Curve(P2Q, x^4 + y^4 + z^4);
autQ := AutomorphismGroup(CQ);
printf "|Aut(C/Q)| = %o\n", #autQ;

printf "\nThe full automorphism group of order 96 is defined over Q(i) = Q(sqrt(-1)).\n";
printf "Over Q, only %o automorphisms are visible (the coordinate permutations\n", #autQ;
printf "and sign changes, i.e., the subgroup (Z/2Z)^2 ⋊ S_3 of order 24).\n";
