/*******************************************************************************
 * test_hurwitz_group_search.m
 *
 * Purpose:
 *   Search for Hurwitz groups of a given genus. A Hurwitz group is a finite
 *   group G that can be generated by elements g1, g2, g3 with orders 2, 3, 7
 *   respectively, where g1*g2 = g3. Such groups arise as automorphism groups
 *   of Hurwitz curves (compact Riemann surfaces achieving the Hurwitz bound
 *   |Aut(C)| = 84(g-1)).
 *
 * Method:
 *   For each genus g in a specified range, compute N = 84(g-1) (the order of
 *   a Hurwitz group of genus g), then iterate through all groups of order N
 *   in Magma's SmallGroups database and check if they admit a spherical
 *   generating triple of type (2, 3, 7).
 *
 * Output:
 *   Prints (genus, group) pairs for all Hurwitz groups found.
 *
 * Related files:
 *   - compute_examples.m: Uses Hurwitz curves as examples
 *   - group_reps.m: Group representation computations
 *
 * References:
 *   - Hurwitz, A. (1893). "Ueber algebraische Gebilde mit eindeutigen
 *     Transformationen in sich"
 ******************************************************************************/

// Check if group G admits a spherical generating triple of type (2, 3, 7)
searchG := function(G)
    for g1 in G do
        if Order(g1) eq 2 then
            for g2 in G do
                if Order(g2) eq 3 then
                    g3 := g1*g2;
                    if (Order(g3) eq 7) and #G eq Order(sub<G | g1, g2, g3>) then
                        return true;
                    end if;
                end if;
            end for;
        end if;
    end for;
    return false;
end function;

// Search for Hurwitz groups of genus 19 through 21
for g in [19..21] do
    N := 84*(g-1);
    grps := SmallGroups(N);
    for G in grps do
        if searchG(G) then
            print g, G;
        end if;
    end for;
end for;
