import "../invariants.m": K2, HodgeDiamond, ComputeBasket, SegreNumber, MyPi1;
import "../group_reps.m": computeRationalCohomology;

for n in [5..20] do

    S := SymmetricGroup(n);
    
    // get conjugacy classes
    conj := ConjugacyClasses(S);
    
    // find an element of order 2
    g2 := Id(S);
    for c in conj do
        if c[1] eq 2 then
            g2 := c[3];
            // loop over all elements of order 3
            for g3 in S do
                if Order(g3) eq 3 then
                    
                    // set G to be the group generated by g2 and g3
                    G := sub<S | g2, g3>;
                    
                    seq := [g2, g2, g3, g3^(-1)];
                    ksquare := K2([seq, seq], G);
                    if ksquare le 0 then
                        print G;
                        print "K2 = ", ksquare;
                        HodgeDiamond([seq, seq], G);
                    end if;
                end if;
            end for;
        end if;
    end for;


end for;