import "../invariants.m": K2, HodgeDiamond, ComputeBasket, SegreNumber, MyPi1;
import "../group_reps.m": computeRationalCohomology;


for n in [5..30] do

    S := SymmetricGroup(n);
    
    // get conjugacy classes
    conj := ConjugacyClasses(S);
    
    // find an element of order 3
    a := Id(S);
    for c in conj do
        if c[1] eq 2 then
            a := c[3];
            // loop over all elements of order n
            for b in S do
                if Order(b) eq n and Order(a*b) eq n then
                    
                    // set G to be the group generated by g2 and g3
                    G := sub<S | a, b>;
                    
                    seq := [a, b, (a*b)^(-1)];
                    ksquare := K2([seq, seq], G);
                    if ksquare le 0 then
                        print G;
                        print "K2 = ", ksquare;
                        HodgeDiamond([seq, seq], G);
                        break;
                    end if;
                end if;
            end for;
        end if;
    end for;


end for;
