import "../invariants.m": K2, HodgeDiamond, ComputeBasket, SegreNumber, MyPi1;
import "../group_reps.m": computeRationalCohomology;

if false then

for n in [5..20] do

    S := SymmetricGroup(n);
    
    // get conjugacy classes
    conj := ConjugacyClasses(S);
    
    // find an element of order 3
    a := Id(S);
    for c in conj do
        if c[1] eq 3 then
            a := c[3];
            // loop over all elements of order 3
            for b in S do
                if Order(b) eq 3 and Order(a*b) eq 4 then
                    
                    // set G to be the group generated by g2 and g3
                    G := sub<S | a, b>;
                    
                    seq := [a, b, (a*b)^(-1)];
                    ksquare := K2([seq, seq], G);
                    if ksquare le 0 then
                        print G;
                        print "K2 = ", ksquare;
                        HodgeDiamond([seq, seq], G);
                    end if;
                end if;
            end for;
        end if;
    end for;


end for;

end if;

S := SymmetricGroup(9);

a := S!(1, 2, 3)(4, 5, 6)(7, 8, 9);
b := S!(1, 3, 4)(2, 5, 8)(6, 9, 7);

G := sub<S | a, b>;

seq := [a, b, (a*b)^(-1)];
ksquare := K2([seq, seq], G);
print ksquare;

HodgeDiamond([seq, seq], G);